#spring.application.name=springHealthApp
##spring.mvc.view.prefix=/WEB-INF/views/
##spring.mvc.view.suffix=.jsp
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/health_diary?serverTimezone=Asia/Seoul&autoReconnect=true&useSSL=false
#
#spring.datasource.username=root
#spring.datasource.password=qwer1234
#
#mybatis.mapper-locations=classpath:mappers/*.xml
#mybatis.type-aliases-package=com.server.healthapp.springHealthApp.dto
#
#debug=true
#logging.level.org.mybatis=DEBUG
#logging.level.org.springframework=DEBUG
#
#jwt.header=Authorization
#jwt.token.secret=9c25b2d72c78898f1e8567e967f6978e722293909ad2b813e199b10fa47c911026c08189b23a6a69584ef30b147136f8826b57813b4fb8274e26c33ef27d0e73
#



spring:
  application:
    name: springHealthApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_diary?serverTimezone=Asia/Seoul&autoReconnect=true&useSSL=false
    username: root
    password: qwer1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
debug: true
logging:
    level:
      org:
        mybatis: DEBUG
        springframework: DEBUG

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.server.healthapp.springHealthApp.dto

jwt:
  secret: "7e70be9c6489c38ae3ccd1f82c1fac42ac5e5d80cea0eed11a2d0420d5e30862"
